# Generated by Django 5.1.2 on 2024-11-03 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0003_photomodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonteCarloIntegrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField()),
                ('lower_bound', models.FloatField()),
                ('upper_bound', models.FloatField()),
                ('estimated_area', models.FloatField(blank=True, null=True)),
                ('graphic', models.ImageField(blank=True, null=True, upload_to='media/solved')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='PhotoModel',
        ),
    ]
