# Generated by Django 5.1.2 on 2024-11-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0008_alter_montecarlointegrationmodel_graphic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montecarlointegrationmodel',
            name='time_needed',
        ),
    ]
