# Generated by Django 5.1.2 on 2024-11-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realization', '0009_remove_montecarlointegrationmodel_time_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='montecarlointegrationmodel',
            name='time_needed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
